import { Trigger } from "@/types/Trigger";

const triggers: Trigger[] = [
  {
    id: 1,
    name: "Tiny Velcro Bows",
    url: "https://youtu.be/hUL_JdnWdEw",
    start: 259,
    end: 280,
  },
  {
    id: 2,
    name: "Water Bead Pouch",
    url: "https://youtu.be/02xYGcihZCE",
    start: 1367,
    end: 1384,
  },
  {
    id: 3,
    name: "Foldable Book Light",
    url: "https://youtu.be/Jjai60__8TY",
    start: 856,
    end: 877,
  },
  {
    id: 4,
    name: "Wax Cubes",
    url: "https://youtu.be/8s2WrDhdS08",
    start: 1797,
    end: 1820,
  },
  {
    id: 5,
    name: "Silicone Brush",
    url: "https://youtu.be/yCATglIFf_I",
    start: 749,
    end: 768,
  },
  {
    id: 6,
    name: "Ear Pick",
    url: "https://youtu.be/yCATglIFf_I",
    start: 1895,
    end: 1921,
  },
  {
    id: 7,
    name: "Mic Brushing",
    url: "https://youtu.be/HUlpQaAnDd0",
    start: 1286,
    end: 1311,
  },
  {
    id: 8,
    name: "Lens Brushing",
    url: "https://youtu.be/HUlpQaAnDd0",
    start: 1483,
    end: 1504,
  },
  {
    id: 9,
    name: "Toaster Coaster Tapping",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 445,
    end: 469,
  },
  {
    id: 10,
    name: "Silicone Cup Tapping",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 668,
    end: 695,
  },
  {
    id: 11,
    name: "Mic Scratching",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 854,
    end: 877,
  },
  {
    id: 12,
    name: "Hand Cream Tube Tapping",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 929,
    end: 951,
  },
  {
    id: 13,
    name: "Makeup Case Tapping",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 1097,
    end: 1123,
  },
  {
    id: 14,
    name: "Journal Tapping",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 1431,
    end: 1454,
  },
  {
    id: 15,
    name: "Dish Brush",
    url: "https://youtu.be/VD1i7XBQC6Q",
    start: 300,
    end: 325,
  },
  {
    id: 16,
    name: "Jar Sounds",
    url: "https://youtu.be/VD1i7XBQC6Q",
    start: 423,
    end: 453,
  },
  {
    id: 17,
    name: "Dog Hair Coarse Foam Sponge",
    url: "https://youtu.be/VD1i7XBQC6Q",
    start: 627,
    end: 650,
  },
  {
    id: 18,
    name: "Dream Oil Jar",
    url: "https://youtu.be/VD1i7XBQC6Q",
    start: 884,
    end: 910,
  },
  {
    id: 19,
    name: "Wood Tapping / Brush Sounds",
    url: "https://youtu.be/VD1i7XBQC6Q",
    start: 1030,
    end: 1048,
  },
];

export default triggers;
