import { CREATOR_ID } from "@/types/Creator";
import { Trigger } from "@/types/Trigger";

const triggers: Trigger[] = [
  {
    id: 1,
    creatorId: CREATOR_ID.Gibi,
    name: "Tiny Velcro Bows",
    url: "https://youtu.be/hUL_JdnWdEw",
    start: 259,
    end: 280,
    noTalking: false,
  },
  {
    id: 2,
    creatorId: CREATOR_ID.Gibi,
    name: "Water Bead Pouch",
    url: "https://youtu.be/02xYGcihZCE",
    start: 1367,
    end: 1384,
    noTalking: false,
  },
  {
    id: 3,
    creatorId: CREATOR_ID.Gibi,
    name: "Foldable Book Light",
    url: "https://youtu.be/Jjai60__8TY",
    start: 856,
    end: 877,
    noTalking: true,
  },
  {
    id: 4,
    creatorId: CREATOR_ID.Gibi,
    name: "Wax Cubes",
    url: "https://youtu.be/8s2WrDhdS08",
    start: 1797,
    end: 1820,
    noTalking: false,
  },
  {
    id: 5,
    creatorId: CREATOR_ID.Gibi,
    name: "Silicone Brush",
    url: "https://youtu.be/yCATglIFf_I",
    start: 749,
    end: 768,
    noTalking: false,
  },
  {
    id: 6,
    creatorId: CREATOR_ID.Gibi,
    name: "Ear Pick",
    url: "https://youtu.be/yCATglIFf_I",
    start: 1895,
    end: 1921,
    noTalking: false,
  },
  {
    id: 7,
    creatorId: CREATOR_ID.Gibi,
    name: "Mic Brushing",
    url: "https://youtu.be/HUlpQaAnDd0",
    start: 1286,
    end: 1311,
    noTalking: false,
  },
  {
    id: 8,
    creatorId: CREATOR_ID.Gibi,
    name: "Lens Brushing",
    url: "https://youtu.be/HUlpQaAnDd0",
    start: 1483,
    end: 1504,
    noTalking: false,
  },
  {
    id: 9,
    creatorId: CREATOR_ID.Gibi,
    name: "Toaster Coaster Tapping",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 445,
    end: 469,
    noTalking: true,
  },
  {
    id: 10,
    creatorId: CREATOR_ID.Gibi,
    name: "Silicone Cup Tapping",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 668,
    end: 695,
    noTalking: true,
  },
  {
    id: 11,
    creatorId: CREATOR_ID.Gibi,
    name: "Mic Scratching",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 854,
    end: 877,
    noTalking: true,
  },
  {
    id: 12,
    creatorId: CREATOR_ID.Gibi,
    name: "Hand Cream Tube Tapping",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 929,
    end: 951,
    noTalking: false,
  },
  {
    id: 13,
    creatorId: CREATOR_ID.Gibi,
    name: "Makeup Case Tapping",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 1097,
    end: 1123,
    noTalking: true,
  },
  {
    id: 14,
    creatorId: CREATOR_ID.Gibi,
    name: "Journal Tapping",
    url: "https://youtu.be/3dfl5MBMsUE",
    start: 1431,
    end: 1454,
    noTalking: true,
  },
  {
    id: 15,
    creatorId: CREATOR_ID.Gibi,
    name: "Dish Brush",
    url: "https://youtu.be/VD1i7XBQC6Q",
    start: 300,
    end: 325,
    noTalking: true,
  },
  {
    id: 16,
    creatorId: CREATOR_ID.Gibi,
    name: "Jar Sounds",
    url: "https://youtu.be/VD1i7XBQC6Q",
    start: 423,
    end: 453,
    noTalking: false,
  },
  {
    id: 17,
    creatorId: CREATOR_ID.Gibi,
    name: "Dog Hair Coarse Foam Sponge",
    url: "https://youtu.be/VD1i7XBQC6Q",
    start: 627,
    end: 650,
    noTalking: true,
  },
  {
    id: 18,
    creatorId: CREATOR_ID.Gibi,
    name: "Dream Oil Jar",
    url: "https://youtu.be/VD1i7XBQC6Q",
    start: 884,
    end: 910,
    noTalking: false,
  },
  {
    id: 19,
    creatorId: CREATOR_ID.Gibi,
    name: "Wood Tapping / Brush Sounds",
    url: "https://youtu.be/VD1i7XBQC6Q",
    start: 1030,
    end: 1048,
    noTalking: true,
  },
  {
    id: 20,
    creatorId: CREATOR_ID.Gibi,
    name: "Finger Sized Dog Toothbrushes",
    url: "https://youtu.be/jgRq4SCwMwA",
    start: 1078,
    end: 1105,
    noTalking: true,
  },
  {
    id: 21,
    creatorId: CREATOR_ID.Gibi,
    name: "Macro Keyboard",
    url: "https://youtu.be/jgRq4SCwMwA",
    start: 1243,
    end: 1265,
    noTalking: true,
  },
  {
    id: 22,
    creatorId: CREATOR_ID.Gibi,
    name: "Sunglasses",
    url: "https://youtu.be/jgRq4SCwMwA",
    start: 1514,
    end: 1525,
    noTalking: true,
  },
  {
    id: 23,
    creatorId: CREATOR_ID.Gibi,
    name: "Plastic Disc Tapping",
    url: "https://youtu.be/fbW-ewvl9z0",
    start: 309,
    end: 332,
    noTalking: false,
  },
  {
    id: 24,
    creatorId: CREATOR_ID.Gibi,
    name: "Rolling Wooden Balls",
    url: "https://youtu.be/fbW-ewvl9z0",
    start: 1194,
    end: 1222,
    noTalking: true,
  },
  {
    id: 25,
    creatorId: CREATOR_ID.Gibi,
    name: "Silicone Cup Scratching",
    url: "https://youtu.be/t23YdznJ6-8",
    start: 484,
    end: 506,
    noTalking: true,
  },
  {
    id: 26,
    creatorId: CREATOR_ID.Gibi,
    name: "Watermelon Dog Toy",
    url: "https://youtu.be/t23YdznJ6-8",
    start: 1023,
    end: 1044,
    noTalking: true,
  },
  {
    id: 27,
    creatorId: CREATOR_ID.Gibi,
    name: "Cardboard Tube",
    url: "https://youtu.be/t23YdznJ6-8",
    start: 1339,
    end: 1364,
    noTalking: true,
  },
  {
    id: 28,
    creatorId: CREATOR_ID.Gibi,
    name: "Lotion Bottle Tapping",
    url: "https://youtu.be/t23YdznJ6-8",
    start: 1664,
    end: 1688,
    noTalking: true,
  },
  {
    id: 29,
    creatorId: CREATOR_ID.Gibi,
    name: "Heat Sensitive Foam Pad",
    url: "https://youtu.be/02xYGcihZCE",
    start: 2733,
    end: 2756,
    noTalking: false,
  },
  {
    id: 30,
    creatorId: CREATOR_ID.Gibi,
    name: "Tapping On A Small Box",
    url: "https://youtu.be/HUlpQaAnDd0",
    start: 433,
    end: 455,
    noTalking: false,
  },
  {
    id: 31,
    creatorId: CREATOR_ID.Gibi,
    name: "Tapping On A Milk Carton",
    url: "https://youtu.be/-8BNDacMZUk",
    start: 701,
    end: 722,
    noTalking: true,
  },
  {
    id: 32,
    creatorId: CREATOR_ID.Gibi,
    name: "Real Toast Scratching",
    url: "https://youtu.be/-8BNDacMZUk",
    start: 1362,
    end: 1386,
    noTalking: true,
  },
  {
    id: 33,
    creatorId: CREATOR_ID.Gibi,
    name: "Tapping On A Soda Can",
    url: "https://youtu.be/m2u1C2Ko7K8",
    start: 528,
    end: 553,
    noTalking: true,
  },
  {
    id: 34,
    creatorId: CREATOR_ID.Gibi,
    name: "Tapping On A Popsicle Stick",
    url: "https://youtu.be/m2u1C2Ko7K8",
    start: 1582,
    end: 1610,
    noTalking: true,
  },
  {
    id: 35,
    creatorId: CREATOR_ID.Gibi,
    name: "Soap Wrapper",
    url: "https://youtu.be/m2u1C2Ko7K8",
    start: 2916,
    end: 2942,
    noTalking: true,
  },
  {
    id: 36,
    creatorId: CREATOR_ID.Gibi,
    name: "Mechanical Keyboard",
    url: "https://youtu.be/dhQsq22QYKM",
    start: 1459,
    end: 1483,
    noTalking: true,
  },
  {
    id: 37,
    creatorId: CREATOR_ID.Gibi,
    name: "Coloring On A Crinkly Cartoon Ball",
    url: "https://youtu.be/ereUyeiKI5Y",
    start: 438,
    end: 472,
    noTalking: false,
  },
  {
    id: 38,
    creatorId: CREATOR_ID.Gibi,
    name: "Liquid Sounds",
    url: "https://youtu.be/_fD9nfGjO_A",
    start: 967,
    end: 992,
    noTalking: false,
  },
  {
    id: 39,
    creatorId: CREATOR_ID.Gibi,
    name: "Coarse Sponge Sounds",
    url: "https://youtu.be/_fD9nfGjO_A",
    start: 1149,
    end: 1168,
    noTalking: true,
  },
  {
    id: 40,
    creatorId: CREATOR_ID.Gibi,
    name: "Earpicks On The Mics",
    url: "https://youtu.be/_fD9nfGjO_A",
    start: 1475,
    end: 1502,
    noTalking: true,
  },
  {
    id: 41,
    creatorId: CREATOR_ID.Darling,
    name: "Cork Board Scratching",
    url: "https://youtu.be/t0TANqdtjkI",
    start: 451,
    end: 478,
    noTalking: true,
  },
  {
    id: 42,
    creatorId: CREATOR_ID.Darling,
    name: "Mesh Bag",
    url: "https://youtu.be/t0TANqdtjkI",
    start: 528,
    end: 559,
    noTalking: true,
  },
  {
    id: 43,
    creatorId: CREATOR_ID.Darling,
    name: "Water Spraying Sounds",
    url: "https://youtu.be/t0TANqdtjkI",
    start: 2039,
    end: 2059,
    noTalking: true,
  },
  {
    id: 44,
    creatorId: CREATOR_ID.Darling,
    name: "Purse Tapping",
    url: "https://youtu.be/rRRbNBjvYQ0",
    start: 507,
    end: 525,
    noTalking: true,
  },
  {
    id: 45,
    creatorId: CREATOR_ID.Darling,
    name: "Planner Tapping",
    url: "https://youtu.be/rRRbNBjvYQ0",
    start: 1501,
    end: 1525,
    noTalking: true,
  },
  {
    id: 46,
    creatorId: CREATOR_ID.Darling,
    name: "Mic Scratching",
    url: "https://youtu.be/rRRbNBjvYQ0",
    start: 1880,
    end: 1909,
    noTalking: true,
  },
  {
    id: 47,
    creatorId: CREATOR_ID.Darling,
    name: "Hexagonal Fidget Toy",
    url: "https://youtu.be/mXdk4Eg_1S0",
    start: 190,
    end: 219,
    noTalking: false,
  },
  {
    id: 48,
    creatorId: CREATOR_ID.Darling,
    name: "Button Fidget Toy",
    url: "https://youtu.be/mXdk4Eg_1S0",
    start: 502,
    end: 521,
    noTalking: true,
  },
  {
    id: 49,
    creatorId: CREATOR_ID.Darling,
    name: "Sequin Star Pillow",
    url: "https://youtu.be/mXdk4Eg_1S0",
    start: 952,
    end: 976,
    noTalking: true,
  },
  {
    id: 50,
    creatorId: CREATOR_ID.Darling,
    name: "iPad Tapping",
    url: "https://youtu.be/mXdk4Eg_1S0",
    start: 1585,
    end: 1609,
    noTalking: true,
  },
];

export default triggers;
